INSERT INTO EVENT (NAME, DESCRIPTION, DATE, TIME, LOCATION) VALUES ('Java User Group', 'Discuss Java 9', '2017-10-25', '10:30:00', 'JavaLand');
INSERT INTO EVENT (NAME, DESCRIPTION, DATE, TIME, LOCATION) VALUES ('Spring User Group', 'Discuss Spring 5', '2017-10-26', '10:30:00', 'SpringLand');
INSERT INTO EVENT (NAME, DESCRIPTION, DATE, TIME, LOCATION) VALUES ('Java User Helm', 'Discuss Java 23', '2025-10-25', '09:45:00', 'TimeLand');


INSERT INTO `USERS` (NICK, PASSWORD, INIT_TOKEN, UPDATED_TOKEN) VALUES ('admin', '$2a$10$bfFxpW991gkweAOOL.dJw.SZkGvOL2f7wC7VEPH3/9JmHdnr1QV0a', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()); --abcde
INSERT INTO `USERS` (NICK, PASSWORD, INIT_TOKEN, UPDATED_TOKEN)  VALUES ('HGOME16', '$2a$10$RStWWx9clVFhNuhkDSgd9.lKKWE1Y4Y19Qhi23mDx/ybhMG8Sy5YK', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()); --1234
    -- SELECT * FROM (SELECT 'HGOME16' c1, '$2a$10$RStWWx9clVFhNuhkDSgd9.lKKWE1Y4Y19Qhi23mDx/ybhMG8Sy5YK' c2, sysdate() c3, sysdate() c4)t
    -- WHERE NOT EXISTS (SELECT 1 FROM `USER`);