CREATE TABLE IF NOT EXISTS EVENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    DATE DATE NOT NULL,
    TIME TIME NOT NULL,
    LOCATION VARCHAR(255) NOT NULL
);