CREATE TABLE IF NOT EXISTS `USERS` (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NICK VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    INIT_TOKEN DATE NOT NULL,
    UPDATED_TOKEN DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS `EVENT` (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    DATE DATE NOT NULL,
    TIME TIME NOT NULL,
    LOCATION VARCHAR(255) NOT NULL
);

